using System;
using System.Collections.Generic;
using System.Text;

namespace MineCase.Server.World
{
    public enum BlockId : uint
    {
        Air = 0,
        Stone = 1,
        Grass = 2,
        Dirt = 3,
        Cobblestone = 4,
        WoodPlanks = 5,
        Sapling = 6,
        Bedrock = 7,
        Water = 8,
        StationaryWater = 9,
        Lava = 10,
        StationaryLava = 11,
        Sand = 12,
        Gravel = 13,
        GoldOre = 14,
        IronOre = 15,
        CoalOre = 16,
        Wood = 17,
        Leaves = 18,
        Sponge = 19,
        Glass = 20,
        LapisLazuliOre = 21,
        LapisLazuliBlock = 22,
        Dispenser = 23,
        Sandstone = 24,
        NoteBlock = 25,
        Bed = 26,
        PoweredRail = 27,
        DetectorRail = 28,
        StickyPiston = 29,
        Cobweb = 30,
        Grass = 31,
        DeadBush = 32,
        Piston = 33,
        PistonHead = 34,
        Wool = 35,
        BlockMovedByPiston = 36,
        Dandelion = 37,
        Poppy = 38,
        BrownMushroom = 39,
        RedMushroom = 40,
        BlockOfGold = 41,
        BlockOfIron = 42,
        DoubleStoneSlab = 43,
        StoneSlab = 44,
        Bricks = 45,
        TNT = 46,
        Bookshelf = 47,
        MossStone = 48,
        Obsidian = 49,
        Torch = 50,
        Fire = 51,
        MonsterSpawner = 52,
        OakWoodStairs = 53,
        Chest = 54,
        RedstoneWire = 55,
        DiamondOre = 56,
        BlockOfDiamond = 57,
        CraftingTable = 58,
        Wheat = 59,
        Farmland = 60,
        Furnace = 61,
        BurningFurnace = 62,
        StandingSign = 63,
        OakDoor = 64,
        Ladder = 65,
        Rail = 66,
        CobblestoneStairs = 67,
        WallSign = 68,
        Lever = 69,
        StonePressurePlate = 70,
        IronDoor = 71,
        WoodenPressurePlate = 72,
        RedstoneOre = 73,
        GlowingRedstoneOre = 74,
        RedstoneTorchInactive = 75,
        RedstoneTorchActive = 76,
        StoneButton = 77,
        SnowLayer = 78,
        Ice = 79,
        Snow = 80,
        Cactus = 81,
        Clay = 82,
        SugarCane = 83,
        Jukebox = 84,
        OakFence = 85,
        Pumpkin = 86,
        Netherrack = 87,
        SoulSand = 88,
        Glowstone = 89,
        NetherPortal = 90,
        JackLantern = 91,
        Cake = 92,
        RedstoneRepeaterInactive = 93,
        RedstoneRepeaterActive = 94,
        StainedGlass = 95,
        Trapdoor = 96,
        MonsterEgg = 97,
        StoneBricks = 98,
        BrownMushroomBlock = 99,
        RedMushroomBlock = 100,
        IronBars = 101,
        GlassPane = 102,
        Melon = 103,
        PumpkinStem = 104,
        MelonStem = 105,
        Vines = 106,
        FenceGate = 107,
        BrickStairs = 108,
        StoneBrickStairs = 109,
        Mycelium = 110,
        LilyPad = 111,
        NetherBrick = 112,
        NetherBrickFence = 113,
        NetherBrickStairs = 114,
        NetherWart = 115,
        EnchantmentTable = 116,
        BrewingStand = 117,
        Cauldron = 118,
        EndPortal = 119,
        EndPortalFrame = 120,
        EndStone = 121,
        DragonEgg = 122,
        RedstoneLampInactive = 123,
        RedstoneLampActive = 124,
        DoubleWoodenSlab = 125,
        WoodenSlab = 126,
        Cocoa = 127,
        SandstoneStairs = 128,
        EmeraldOre = 129,
        EnderChest = 130,
        TripwireHook = 131,
        Tripwire = 132,
        BlockOfEmerald = 133,
        SpruceWoodStairs = 134,
        BirchWoodStairs = 135,
        JungleWoodStairs = 136,
        CommandBlock = 137,
        Beacon = 138,
        CobblestoneWall = 139,
        FlowerPot = 140,
        Carrot = 141,
        Potato = 142,
        WoodenButton = 143,
        Mobhead = 144,
        Anvil = 145,
        TrappedChest = 146,
        WeightedPressurePlateLight = 147,
        WeightedPressurePlateHeavy = 148,
        RedstoneComparator = 149,
        RedstoneComparatorDeprecated = 150,
        DaylightSensor = 151,
        BlockOfRedstone = 152,
        NetherQuartzOre = 153,
        Hopper = 154,
        BlockOfQuartz = 155,
        QuartzStairs = 156,
        ActivatorRail = 157,
        Dropper = 158,
        StainedClay = 159,
        StainedGlassPane = 160,
        Leaves2 = 161,
        Wood2 = 162,
        AcaciaWoodStairs = 163,
        DarkOakWoodStairs = 164,
        SlimeBlock = 165,
        Barrier = 166,
        IronTrapdoor = 167,
        Prismarine = 168,
        SeaLantern = 169,
        HayBale = 170,
        Carpet = 171,
        HardenedClay = 172,
        BlockOfCoal = 173,
        PackedIce = 174,
        LargeFlowers = 175,
        StandingBanner = 176,
        WallBanner = 177,
        InvertedDaylightSensor = 178,
        RedSandstone = 179,
        RedSandstoneStairs = 180,
        DoubleRedSandstoneSlab = 181,
        RedSandstoneSlab = 182,
        SpruceFenceGate = 183,
        BirchFenceGate = 184,
        JungleFenceGate = 185,
        DarkOakFenceGate = 186,
        AcaciaFenceGate = 187,
        SpruceFence = 188,
        BirchFence = 189,
        JungleFence = 190,
        DarkOakFence = 191,
        AcaciaFence = 192,
        SpruceDoor = 193,
        BirchDoor = 194,
        JungleDoor = 195,
        AcaciaDoor = 196,
        DarkOakDoor = 197,
        EndRod = 198,
        ChorusPlant = 199,
        ChorusFlower = 200,
        PurpurBlock = 201,
        PurpurPillar = 202,
        PurpurStairs = 203,
        PurpurDoubleSlab = 204,
        PurpurSlab = 205,
        EndStoneBricks = 206,
        BeetrootSeeds = 207,
        GrassPath = 208,
        EndGateway = 209,
        RepeatingCommandBlock = 210,
        ChainCommandBlock = 211,
        FrostedIce = 212,
        MagmaBlock = 213,
        NetherWartBlock = 214,
        RedNetherBrick = 215,
        BoneBlock = 216,
        StructureVoid = 217,
        Observer = 218,
        WhiteShulkerBox = 219,
        OrangeShulkerBox = 220,
        MagentaShulkerBox = 221,
        LightBlueShulkerBox = 222,
        YellowShulkerBox = 223,
        LimeShulkerBox = 224,
        PinkShulkerBox = 225,
        GrayShulkerBox = 226,
        LightGrayShulkerBox = 227,
        CyanShulkerBox = 228,
        PurpleShulkerBox = 229,
        BlueShulkerBox = 230,
        BrownShulkerBox = 231,
        GreenShulkerBox = 232,
        RedShulkerBox = 233,
        BlackShulkerBox = 234,
        WhiteGlazedTerracotta = 235,
        OrangeGlazedTerracotta = 236,
        MagentaGlazedTerracotta = 237,
        LightBlueGlazedTerracotta = 238,
        YellowGlazedTerracotta = 239,
        LimeGlazedTerracotta = 240,
        PinkGlazedTerracotta = 241,
        GrayGlazedTerracotta = 242,
        LightGrayGlazedTerracotta = 243,
        CyanGlazedTerracotta = 244,
        PurpleGlazedTerracotta = 245,
        BlueGlazedTerracotta = 246,
        BrownGlazedTerracotta = 247,
        GreenGlazedTerracotta = 248,
        RedGlazedTerracotta = 249,
        BlackGlazedTerracotta = 250,
        Concrete = 251,
        ConcretePowder = 252,
        StructureBlock = 255
    }

    public struct BlockState : IEquatable<BlockState>
    {
        public uint Id { get; set; }

        public uint MetaValue { get; set; }

        public override bool Equals(object obj)
        {
            return obj is BlockState && Equals((BlockState)obj);
        }

        public bool Equals(BlockState other)
        {
            return Id == other.Id &&
                   MetaValue == other.MetaValue;
        }

        public override int GetHashCode()
        {
            var hashCode = -81208087;
            hashCode = hashCode * -1521134295 + base.GetHashCode();
            hashCode = hashCode * -1521134295 + Id.GetHashCode();
            hashCode = hashCode * -1521134295 + MetaValue.GetHashCode();
            return hashCode;
        }

        public static bool operator ==(BlockState state1, BlockState state2)
        {
            return state1.Equals(state2);
        }

        public static bool operator !=(BlockState state1, BlockState state2)
        {
            return !(state1 == state2);
        }
    }
}
