version: 1.0.0-alpha1-{build}
image: Visual Studio 2017
before_build:
- ps: >-
    cd src

    dotnet restore

    choco install opencover.portable

    choco install codecov

    cd MineCase.ControlPanel

    npm install

    cd ..
build:
  project: ./src/
  verbosity: minimal
test_script:
- ps: >-
    cd ..\tests

    OpenCover.Console.exe -oldstyle -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test" -output:".\test_coverage.xml"

    codecov -f "test_coverage.xml"