using System;
using System.Collections.Generic;
using System.Text;

namespace MineCase
{
    public enum EntityId : uint
    {
        DroppedItem = 1,
        ExperienceOrb = 2,
        AreaEffectCloud = 3,
        LeadKnot = 8,
        Painting = 9,
        ItemFrame = 18,
        ArmorStand = 30,
        EvocationFangs = 33,
        EnderCrystal = 200,
        ThrownEgg = 7,
        ShotArrow = 10,
        ThrownSnowball = 11,
        GhastFireball = 12,
        BlazeFireball = 13,
        ThrownEnderPearl = 14,
        ThrownEyeOfEnder = 15,
        ThrownSplashPotion = 16,
        ThrownBottleEnchanting = 17,
        WitherSkull = 19,
        FireworkRocket = 22,
        ShotSpectralArrow = 24,
        ShulkerBullet = 25,
        DragonFireball = 26,
        LlamaSpit = 104,
        PrimedTnt = 20,
        FallingBlock = 21,
        MinecartWithCommandBlock = 40,
        Boat = 41,
        Minecart = 42,
        MinecartWithChest = 43,
        MinecartWithFurnace = 44,
        MinecartWithTnt = 45,
        MinecartWithHopper = 46,
        MinecartWithSpawner = 47,
        ElderGuardian = 1,
        WitherSkeleton = 2,
        Stray = 3,
        Husk = 4,
        ZombieVillager = 5,
        Evoker = 6,
        Vex = 7,
        Vindicator = 8,
        Illusioner = 9,
        Creeper = 10,
        Skeleton = 11,
        Spider = 12,
        Giant = 13,
        Zombie = 14,
        Slime = 15,
        Ghast = 16,
        ZombiePigman = 17,
        Enderman = 18,
        CaveSpider = 19,
        Silverfish = 20,
        Blaze = 21,
        MagmaCube = 22,
        EnderDragon = 23,
        Wither = 24,
        Witch = 25,
        Endermite = 26,
        Guardian = 27,
        Shulker = 28,
        SkeletonHorse = 29,
        ZombieHorse = 30,
        Donkey = 31,
        Mule = 32,
        Bat = 33,
        Pig = 34,
        Sheep = 35,
        Cow = 36,
        Chicken = 37,
        Squid = 38,
        Wolf = 39,
        Mooshroom = 40,
        SnowGolem = 41,
        Ocelot = 42,
        IronGolem = 43,
        Horse = 44,
        Rabbit = 45,
        PolarBear = 46,
        Llama = 47,
        Parrot = 48,
        Villager = 49
    }
}
