using System;
using System.Collections.Generic;
using System.Text;

namespace MineCase
{
    public enum EntityId : uint
    {
        DroppedItem = 1,
        ExperienceOrb = 2,
        AreaEffectCloud = 3,
        LeadKnot = 8,
        Painting = 9,
        ItemFrame = 18,
        ArmorStand = 30,
        EvocationFangs = 33,
        EnderCrystal = 200,
        ThrownEgg = 7,
        ShotArrow = 10,
        ThrownSnowball = 11,
        GhastFireball = 12,
        BlazeFireball = 13,
        ThrownEnderPearl = 14,
        ThrownEyeOfEnder = 15,
        ThrownSplashPotion = 16,
        ThrownBottleEnchanting = 17,
        WitherSkull = 19,
        FireworkRocket = 22,
        ShotSpectralArrow = 24,
        ShulkerBullet = 25,
        DragonFireball = 26,
        LlamaSpit = 104,
        PrimedTnt = 20,
        FallingBlock = 21,
        MinecartWithCommandBlock = 40,
        Boat = 41,
        Minecart = 42,
        MinecartWithChest = 43,
        MinecartWithFurnace = 44,
        MinecartWithTnt = 45,
        MinecartWithHopper = 46,
        MinecartWithSpawner = 47,
        ElderGuardian = 4,
        WitherSkeleton = 5,
        Stray = 6,
        Husk = 23,
        ZombieVillager = 27,
        Evoker = 34,
        Vex = 35,
        Vindicator = 36,
        Illusioner = 37,
        Creeper = 50,
        Skeleton = 51,
        Spider = 52,
        Giant = 53,
        Zombie = 54,
        Slime = 55,
        Ghast = 56,
        ZombiePigman = 57,
        Enderman = 58,
        CaveSpider = 59,
        Silverfish = 60,
        Blaze = 61,
        MagmaCube = 66,
        EnderDragon = 63,
        Wither = 64,
        Witch = 66,
        Endermite = 67,
        Guardian = 68,
        Shulker = 69,
        SkeletonHorse = 28,
        ZombieHorse = 29,
        Donkey = 31,
        Mule = 32,
        Bat = 65,
        Pig = 90,
        Sheep = 91,
        Cow = 92,
        Chicken = 93,
        Squid = 94,
        Wolf = 95,
        Mooshroom = 96,
        SnowGolem = 97,
        Ocelot = 98,
        IronGolem = 99,
        Horse = 100,
        Rabbit = 101,
        PolarBear = 102,
        Llama = 103,
        Parrot = 105,
        Villager = 120
    }
}
